
version: '3.7'

#
# Docker Compose file for SwarmConfiguration
# This solution are deployed as a Stack Service
# from Portainer, and uses the docker-compose.yml file
# from SnakeApi solution
#
services:
  swarmconfig:
    image: jagdriver/wavesnake:swarmconfig-v1.0.19

    dns:
      - 192.168.1.234

    extra_hosts:
      - "ws04.wavesnake.local:192.168.1.233"
      - "redis.wavesnake.local:192.168.1.233"
      - "api.wavesnake.dk:192.168.1.230"
      - "cnfg.wavesnake.dk:192.168.1.230"

    volumes:
      - "/var/log/snakelogs:/var/snakelogs"
      #- "/opt/containers/swarmconfig/data:/root/wwwroot"

#    restart: always

    labels:
      - "traefik.enable=true"

      # This section id for local http access
      - "traefik.http.routers.config-local.entrypoints=web"
      - "traefik.http.routers.config-local.rule=Host(`config.wavesnake.local`)"
      - "traefik.http.routers.config-local.service=config-local"
      - "traefik.http.services.config-local.loadbalancer.server.port=6040"

      # This section is for external http access
      - "traefik.http.routers.config-external.entrypoints=web"
      - "traefik.http.routers.config-external.rule=Host(`config.wavesnake.dk`)"
      - "traefik.http.routers.config-external.service=config-external"
      - "traefik.http.services.config-external.loadbalancer.server.port=6040"
      - "traefik.http.middlewares.config-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.config-external.middlewares=config-https-redirect"

      # This section is for external https access
      - "traefik.http.routers.config-secure.entrypoints=secure"
      - "traefik.http.routers.config-secure.rule=Host(`config.wavesnake.dk`)"
      - "traefik.http.routers.config-secure.tls=true"
      - "traefik.http.routers.config-secure.tls.certresolver=http"
      - "traefik.http.routers.config-secure.service=config-secure"
      - "traefik.http.services.config-secure.loadbalancer.server.port=6040"

    networks:
      - traefik-public

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    external: true