version: '3.7'
#
# Docker Compose file for Snakeconfig Staging
# This solution are deployed as a Stack Service
# from Portainer
# 

services:
  SnakeApi:
    image: jagdriver/snakeapps:snakeconfig-staging

    ports:
      - "2100:2100"
      
    networks:
      - traefik-public

    secrets:
      - SwarmSecret

    volumes:
      - "/var/snakelogs/snakeapi:/var/log/snakelogs"
      - "/var/containers/configuration:/opt/containers/configuration"

secrets:
  SwarmSecret:
    external: true

networks:
  traefik-public:
    external: true