version: '3'

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
      - 35729:35729

    networks:
      - traefik-public

    volumes:
      - ./docs:/app/docs
      - ./website/blog:/app/website/blog
      - ./website/core:/app/website/core
      - ./website/i18n:/app/website/i18n
      - ./website/pages:/app/website/pages
      - ./website/static:/app/website/static
      - ./website/sidebars.json:/app/website/sidebars.json
      - ./website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.wsnode == sn01
      labels:
        - "traefik.enable=true"

        # This section id for local http access
        - "traefik.http.routers.docusaurus-local.entrypoints=web"
        - "traefik.http.routers.docusaurus-local.rule=Host(`docs.wavesnake.local`)"
        - "traefik.http.routers.docusaurus-local.service=docusaurus-local"
        - "traefik.http.services.docusaurus-local.loadbalancer.server.port=3000"


networks:
  traefik-public:
    external: true