version: '3.7'
#
# Docker Compose file for Redis
# This solution are deployed to Docker Desktop from Portainer
# as a Swarm Stack Service.
# 
# OBS Testing missing connection to Redis
#
services:
  redis:
    image: redis/redis-stack:latest

    ports:
      - "6379:6379"

    networks:
      - traefik-public

    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  traefik-public:
    external: true