version: '3.7'

#
# Docker Compose file for SnakeApi
# This solution are deployed as a Stack Service
# from Portainer
# 
#
services:
  SnakeApi:
    image: jagdriver/wavesnake:snakeapi
    
    environment:
       ROOT_PASSWORD: "${ROOT_PASSWORD}"
       MANAGER_PASSWORD: "${MANAGER_PASSWORD}"

    networks:
       - traefik-public

    volumes:
       - "/var/log/snakelogs:/var/log/snakelogs"

    extra_hosts:
      - "redis.wavesnake.local:192.168.230.1"
      - "db.wavesnake.local:192.168.230.1"

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.wsnode == ws02
      labels:
        - "traefik.enable=true"

        # This section is for internal http access
        - "traefik.http.routers.api-internal.entrypoints=web"
        - "traefik.http.routers.api-internal.rule=Host(`api.wavesnake.local`,`192.168.1.230`)"
        - "traefik.http.routers.api-internal.service=apisvc-internal"
        - "traefik.http.services.apisvc-internal.loadbalancer.server.port=5000"


        # This section is for external http access
        - "traefik.http.routers.api-external.entrypoints=web"
        - "traefik.http.routers.api-external.rule=Host(`api.wavesnake.dk`)"
        - "traefik.http.routers.api-external.service=apisvc-external"
        - "traefik.http.services.apisvc-external.loadbalancer.server.port=80"
        - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.api-external.middlewares=api-https-redirect"

        # This section is for external https access
        - "traefik.http.routers.api-secure.entrypoints=secure"
        - "traefik.http.routers.api-secure.rule=Host(`api.wavesnake.dk`)"
        - "traefik.http.routers.api-secure.tls=true"
        - "traefik.http.routers.api-secure.tls.certresolver=http"
        - "traefik.http.routers.api-secure.service=apisvc-secure"
        - "traefik.http.services.apisvc-secure.loadbalancer.server.port=5000"

networks:
  traefik-public:
    external: true
