version: '3.7'
#
# Docker Compose file for SnakeApi
# This solution are deployed as a Stack Service
# from Portainer
# 

services:
  SnakeApi:
    image: jagdriver/snakeapps:snakeapi

    depends_on:
      - mysql
      - redis
      
    networks:
      - traefik-public

    secrets:
      - SwarmSecret

    volumes:
      - "/var/log/snakelogs/snakeapi:/var/log/snakelogs"
      - "/mnt/config:/opt/containers"

    extra_hosts:
      - "redis.wavesnake.local:SN01-ETH0-IP"
      - "mqt.wavesnake.local:SN01-ETH0-IP"
      - "api.wavesnake.local:SN01-WLAN0-IP"
      - "sql.wavesnake.local:SN01-WLAN0-IP"
      - "console.wavesnake.local:SN01-WLAN0-IP"
      - "config.wavesnake.local:SN01-WLAN0-IP"
      - "sketch.wavesnake.local:SN01-WLAN0-IP"

    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.wsnode == sn01
      labels:
        - "traefik.enable=true"

        # This section is for internal http access
        - "traefik.http.routers.api-internal.entrypoints=web"
        - "traefik.http.routers.api-internal.rule=Host(`api.wavesnake.local`, Host(`SN01-WLAN0-IP`)"
        - "traefik.http.routers.api-internal.service=apisvc-internal"
        - "traefik.http.services.apisvc-internal.loadbalancer.server.port=5000"


        # This section is for external http access
        - "traefik.http.routers.api-external.entrypoints=web"
        - "traefik.http.routers.api-external.rule=Host(`api.wavesnake.dk`)"
        - "traefik.http.routers.api-external.service=apisvc-external"
        - "traefik.http.services.apisvc-external.loadbalancer.server.port=5000"
        - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.api-external.middlewares=api-https-redirect"

        # This section is for external https access
        - "traefik.http.routers.api-secure.entrypoints=secure"
        - "traefik.http.routers.api-secure.rule=Host(`api.wavesnake.dk`)"
        - "traefik.http.routers.api-secure.tls=true"
        - "traefik.http.routers.api-secure.tls.certresolver=http"
        - "traefik.http.routers.api-secure.service=apisvc-secure"
        - "traefik.http.services.apisvc-secure.loadbalancer.server.port=5000"

secrets:
  SwarmSecret:
    external: true

networks:
  traefik-public:
    external: true
