version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    
    ports:
      - target: 8123
        protocol: tcp
        mode: host

    networks:
      - traefik-public

    privileged: true

    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"

        # This section id for local http access
        - "traefik.tcp.routers.assistantint.entrypoints=homeassistant"
        - "traefik.tcp.routers.asisstantint.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.assistantint.service=homeassistantinternal"
        - "traefik.tcp.services.homeassistantinternal.loadBalancer.server.port=8123"
networks:
   traefik-public:
     external: true