version: '3.7'
#
# Docker Compose file for MySql
# This solution are deployed to Docker Desktop from Portainer
# as a Swarm Stack Service.
#
services:
  mysql:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password

    # When deploying MySql to Docker Desktop, it's a must to add the two
    # environment variables below. Rootpw: e#lg*6O9@cD&&1L9iTX3jFbo@A9G%#78
    environment:
       MYSQL_ROOT_PASSWORD: "wavesnake"
       MYSQL_ROOT_HOST: "%"
       
       #
       # Portainer environment variables that must be configured before deployment:
       # ROOT_PASSWORD, ROOT_HOST must be "%"

    networks:
      - traefik-public

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
      - mode: host
    volumes:
      - /Users/nielsjorgennielsen/sqldata:/var/lib/mysql

    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  traefik-public:
    external: true
