version: '3.7'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik-public
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password "$$2y$$05$$/.uo0TOISIA0iObDNskHkuGHlb/74AhYeDSccTs1V.mzRC8iAYUbm"
    ports:
      - "9000:9000"
      - "8000:8000"
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/containers/portainer/data:/data

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      # This section is for local http access ( at this moment this does not work )
      #- "traefik.http.routers.portainer-local.entrypoints=web"
      #- "traefik.http.routers.portainer-local.rule=Host(`portainer.wavesnake.local`)"
      #- "traefik.http.routers.portainer-local.service=portainer-local"
      ##- "traefik.http.services.portainer-local.loadbalancer.passhostheader=true"
      ##- "traefik.http.services.portainer-local.loadbalancer.sticky=true"
      #- "traefik.http.services.portainer-local.loadbalancer.server.port=9000"

      # This section is for external http access
      - "traefik.http.routers.portainer-external.entrypoints=web"
      - "traefik.http.routers.portainer-external.rule=Host(`adm.wavesnake.dk`)"
      - "traefik.http.routers.portainer-external.service=portainer-external"
      - "traefik.http.services.portainer-external.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.portainer-external.middlewares=portainer-https-redirect"

      # This section is for external https access
      - "traefik.http.routers.portainer-secure.entrypoints=secure"
      - "traefik.http.routers.portainer-secure.rule=Host(`adm.wavesnake.dk`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=http"
      - "traefik.http.routers.portainer-secure.service=portainer-secure"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"


    networks:
      - traefik-public

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

networks:
  traefik-public:
    external: true
    attachable: true
