version: '3.7'

#
# WaveSnake 2020-03-20 
# Docker Compose file for SnakeHistory.
# This solution are deployed from Portainer as a 
# Stack Service.
#
services:

  snakehistory: 
    image: jagdriver/wavesnake:snakehistory

    networks:
      - traefik-public

    volumes:
      - "/var/log/snakelogs:/var/snakelogs"

    extra_hosts:
      - "redis.wavesnake.local:192.168.230.1"
      - "mqt.wavesnake.local:192.168.230.1"
      - "api.wavesnake.local:192.168.230.1"

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.wsnode == ws03

networks:
  traefik-public:
    external: true
